version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "cm-chiyoda"
  - package-ecosystem: "docker"
    directory: "/datadog-agent/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "cm-chiyoda"
  - package-ecosystem: "docker"
    directory: "/python/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "cm-chiyoda"
