name: python
on:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/python.yml"
      - "python/*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Build an image from Dockerfile
        run: |
          docker build -t python:${{ github.sha }} python/

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@bceef37a45815d6c5cfea1861a414ec7dbc00242
        with:
          image-ref: "python:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL"
